### ISSUE TITLE
Pivotal Tracker

### ISSUE THREAD

**Issue by MawsayB** [stevendlc101/liftoff-assignments#1]
Your Pivotal Tracker account cannot be viewed.  Maybe it is set to Private.  [Either make it Public](https://www.pivotaltracker.com/help/articles/using_public_projects/) or add me as a Viewer (msbursac@gmail.com).

**Comment by stevendlc101** [comment]
Sorry. I changed the settings to Public.

**Comment by MawsayB** [comment]
Your stories look great!
