### ISSUE TITLE
Project Planning doc needs a Project Repo Link

### ISSUE THREAD

**Issue by MawsayB** [stevendlc101/liftoff-assignments#5]
See the last heading in the example: https://github.com/LaunchCodeEducation/liftoff-assignments/tree/master/P3-Project_Planning

The link currently under the "Submission Instructions" heading goes to your repo.  You just need to add a "Project Repo Link" heading and put the link under that.  :)

**Comment by stevendlc101** [comment]
Added the Project Repo Link
